### ISSUE TITLE
After installing error generated

### ISSUE THREAD

**Issue by ahaomar** [agilecodex/magento2-brand-slider#1]
After install this module on magento 2.4.2 i am having this errror could you please guide me what to do 

`{"0":"Specified invalid parent id (Acx_Backend::AgileCodex)","1":"#1 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callParent() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:138]\n#2 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:153]\n#3 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callPlugins() called at [generated\\code\\Magento\\Backend\\Model\\Menu\\Builder\\Interceptor.php:32]\n#4 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->getResult() called at [vendor\\magento\\module-backend\\Model\\Menu\\Config.php:148]\n#5 Magento\\Backend\\Model\\Menu\\Config->_initMenu() called at [vendor\\magento\\module-backend\\Model\\Menu\\Config.php:111]\n#6 Magento\\Backend\\Model\\Menu\\Config->getMenu() called at [vendor\\magento\\module-backend\\Model\\Url.php:365]\n#7 Magento\\Backend\\Model\\Url->_getMenu() called at [vendor\\magento\\module-backend\\Model\\Url.php:325]\n#8 Magento\\Backend\\Model\\Url->getStartupPageUrl() called at [vendor\\magento\\module-backend\\Controller\\Adminhtml\\Index\\Index.php:24]\n#9 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index->execute() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:58]\n#10 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callParent() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:138]\n#11 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin.php:51]\n#12 Magento\\Framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:135]\n#13 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:153]\n#14 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins() called at [generated\\code\\Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor.php:23]\n#15 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->execute() called at [vendor\\magento\\framework\\App\\Action\\Action.php:111]\n#16 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\\magento\\module-backend\\App\\AbstractAction.php:151]\n#17 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:58]\n#18 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callParent() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:138]\n#19 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\module-backend\\App\\Action\\Plugin\\Authentication.php:143]\n#20 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:135]\n#21 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:153]\n#22 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins() called at [generated\\code\\Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor.php:32]\n#23 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->dispatch() called at [vendor\\magento\\framework\\App\\FrontController.php:186]\n#24 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\\magento\\framework\\App\\FrontController.php:118]\n#25 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:58]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:138]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\\magento\\framework\\Interception\\Interceptor.php:153]\n#28 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\\code\\Magento\\Framework\\App\\FrontController\\Interceptor.php:23]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\\magento\\framework\\App\\Http.php:116]\n#30 Magento\\Framework\\App\\Http->launch() called at [generated\\code\\Magento\\Framework\\App\\Http\\Interceptor.php:23]\n#31 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\\magento\\framework\\App\\Bootstrap.php:263]\n#32 Magento\\Framework\\App\\Bootstrap->run() called at [pub\\index.php:29]\n","url":"\/admin\/admin\/index\/index\/key\/c3e13078c9d43d3b984d321fcfac013d4c1d987526a344e3521e2685ec64814d\/","script_name":"\/index.php","report_id":"a2991f5e9854cb533c14b569dd3d36bdc72924d9eea97e4c806dc7000e341be9"}
`

**Comment by agilecodex** [comment]
Please try the new updates or download from agilecodex.com
Thanks.
